### ISSUE TITLE
pyxet.get does not allow recursive download of repo root

### ISSUE THREAD

**Issue by assafvayner** [xetdata/pyxet#109]
Getting the following error for this line: `fs.get("xet://<repo>/main/", "data", recursive=True)` (repo name redacted)

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    fs.get("xet://<repo>/main", "data", recursive=True)
  File "/home/ubuntu/pyxet-test/venv/lib/python3.8/site-packages/fsspec/spec.py", line 954, in get
    rpaths = self.expand_path(rpath, recursive=recursive, maxdepth=maxdepth)
  File "/home/ubuntu/pyxet-test/venv/lib/python3.8/site-packages/fsspec/spec.py", line 1150, in expand_path
    out = self.expand_path([path], recursive, maxdepth)
  File "/home/ubuntu/pyxet-test/venv/lib/python3.8/site-packages/fsspec/spec.py", line 1175, in expand_path
    self.find(
  File "/home/ubuntu/pyxet-test/venv/lib/python3.8/site-packages/fsspec/spec.py", line 492, in find
    if withdirs and path != "" and self.isdir(path):
  File "/home/ubuntu/pyxet-test/venv/lib/python3.8/site-packages/pyxet/file_system.py", line 120, in isdir
    return self.isdir_or_branch(path)
  File "/home/ubuntu/pyxet-test/venv/lib/python3.8/site-packages/pyxet/file_system.py", line 125, in isdir_or_branch
    t = self.info(path)["type"]
  File "/home/ubuntu/pyxet-test/venv/lib/python3.8/site-packages/pyxet/file_system.py", line 172, in info
    raise ValueError("Incomplete path: Expecting xet://user/repo/branch/[path]")
ValueError: Incomplete path: Expecting xet://user/repo/branch/[path]
```

Expected behavior take path to be repo root path and download everything.

**Comment by assafvayner** [comment]
issue with script, was missing username in xet url
