### ISSUE TITLE
error uploading Hugging Face dataset to XetHub using pyxet

### ISSUE THREAD

**Issue by sirahd** [xetdata/pyxet#18]
I was following Hugging Face [Cloud storage tutorial](https://huggingface.co/docs/datasets/filesystems) to try to set up XetHub as the storage providers. This is the code snippet I have that reproduces the issue
```python
import pyxet
from datasets import load_dataset_builder

fs = pyxet.XetFS()
output_dir = "xet://sirahd/titanic/main/"
builder = load_dataset_builder("rotten_tomatoes")

with fs.transaction as tr:
    tr.set_commit_message("upload hf data")
    builder.download_and_prepare(output_dir, file_format="arrow")
```
Here, Hugging Face tries to download the `rotten_tomatoes` dataset, converts it into parquet format and uploads to XetHub using its fsspec implementation. The code snippet fails with the following error logs
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 10, in <module>
  File "/Users/samhorradarn/xet/picture-is-worth-a-thousand-words/venv/lib/python3.9/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/Users/samhorradarn/xet/picture-is-worth-a-thousand-words/venv/lib/python3.9/site-packages/datasets/builder.py", line 1717, in _download_and_prepare
    super()._download_and_prepare(
  File "/Users/samhorradarn/xet/picture-is-worth-a-thousand-words/venv/lib/python3.9/site-packages/datasets/builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/Users/samhorradarn/xet/picture-is-worth-a-thousand-words/venv/lib/python3.9/site-packages/datasets/builder.py", line 1638, in _prepare_split
    self._rename(
  File "/Users/samhorradarn/xet/picture-is-worth-a-thousand-words/venv/lib/python3.9/site-packages/datasets/builder.py", line 691, in _rename
    rename(self._fs, src, dst)
  File "/Users/samhorradarn/xet/picture-is-worth-a-thousand-words/venv/lib/python3.9/site-packages/datasets/filesystems/__init__.py", line 69, in rename
    fs.mv(src, dst, recursive=True)
  File "/Users/samhorradarn/xet/picture-is-worth-a-thousand-words/venv/lib/python3.9/site-packages/pyxet/file_system.py", line 576, in mv
    transaction.mv(parsed_path1, parsed_path2)
  File "/Users/samhorradarn/xet/picture-is-worth-a-thousand-words/venv/lib/python3.9/site-packages/pyxet/commit_transaction.py", line 237, in mv
    handler.mv(src_repo_info, dest_repo_info)
  File "/Users/samhorradarn/xet/picture-is-worth-a-thousand-words/venv/lib/python3.9/site-packages/pyxet/commit_transaction.py", line 112, in mv
    self._transaction_handler.mv(src_repo_info.path, dest_repo_info.path)
RuntimeError: Source file rotten_tomatoes-train-00000-00000-of-NNNNN.arrow not found
```
After some digging, it appears Hugging Face library creates `rotten_tomatoes-train-00000-00000-of-NNNNN.arrow` file in the uncommitted transaction and tries to rename it to `rotten_tomatoes-train.arrow` using pyxet fsspec's `mv` implementation. pyxet `mv` implementation checks if the src file exists before allowing `mv` operation to go through. But because the transaction was uncommitted the src file is not visible and ultimately fails with src file not found error.

**Comment by sirahd** [comment]
Minimal reproduction without using `dataset` package below:
```python
import pyxet
fs = pyxet.XetFS()
with fs.transaction as tr:
    tr.set_commit_message("test")
    fs.open("sirahd/titanic/main/foo.csv", "w").write("Hello world!")
    fs.mv("sirahd/titanic/main/foo.csv", "sirahd/titanic/main/bar.csv")
```

**Comment by ylow** [comment]
The easiest way perhaps will be to do `xet cp hf://datasets/rotten_tomatoes xet://...` or something like that I think. A rename mid transaction should be fixable though.

**Comment by ylow** [comment]
Fixed by https://github.com/xetdata/xet-core/pull/82
