### ISSUE TITLE
xet mount fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by znation** [xetdata/pyxet#21]
The `xet mount` command is unable to find the `pyxet` module, but regular Python can:

```
(venv) ➜ xet mount xet://XetHub/RedPajama-Data-1T-Sample/duckdb duckdb
Mounting to "/Users/zach/temp/duckdb"
Cloning into temporary directory "/var/folders/cs/kdfxb73503g7zbm0wqjxpmbm0000gn/T/.tmpoER4ei"
Mounting as a background task...
Traceback (most recent call last):
  File "/Users/zach/venv/bin/xet", line 5, in <module>
    from pyxet.cli import cli
ModuleNotFoundError: No module named 'pyxet'
Traceback (most recent call last):

  File "/Users/zach/venv/bin/xet", line 8, in <module>
    sys.exit(cli())

  File "/Users/zach/venv/lib/python3.9/site-packages/pyxet/cli.py", line 277, in mount
    rpyxet.perform_mount(source.remote, path, source.branch)

RuntimeError: Other("Mount subprocess died unexpectedly. stdout=, stderr=")

(venv) ➜ which python
/Users/zach/venv/bin/python
(venv) ➜ which python3
/Users/zach/venv/bin/python3
(venv) ➜ python3
Python 3.9.17 (main, Jun 20 2023, 17:20:08) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyxet
>>> 
```

**Comment by znation** [comment]
Might be fixed by https://github.com/xetdata/xet-core/pull/69?

**Comment by ylow** [comment]
should be fixed Can you try with the current release?
